name: Generate Podcast Feed

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pyyaml
          # Include any other dependencies here or use a requirements.txt file

      - name: Run Feed Generator
        run: python feed.py

      - name: Push Repo
        run: |
          git config user.name github-actions
          git config user.email suzie.schmitt@hedyandhopp.com
          git add .
          git diff-index --quiet HEAD || git commit -m "Modified Feed"
          git push
